# general settings
name: 019_train_Uformer_dehaze_P256W8_500k_B6G2
model_type: SRModel
scale: 1
num_gpu: 2
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Dehaze
    type: LQGTDataset
    data_type: img
    dataroot_gt: /home/yqliu/projects/ClassSwin/data/Dehaze/clear
    dataroot_lq: /home/yqliu/projects/ClassSwin/data/Dehaze/hazy

    gt_size: 256
    use_flip: true
    use_rot: true
    color: RGB

    # data loader
    num_worker_per_gpu: 3
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SOTS
    type: LQGTDataset
    data_type: img
    dataroot_gt: /home/yqliu/projects/ClassSwin/data/Dehaze/SOTS/indoor/nyuhaze500_square/gt
    dataroot_lq: /home/yqliu/projects/ClassSwin/data/Dehaze/SOTS/indoor/nyuhaze500_square/hazy
    color: RGB

# network structures
network_g:
  type: Uformer
  upscale: 1
  in_chans: 3
  img_size: 256
  window_size: 8
  depths: [2, 2, 2, 2, 2, 2, 2, 2, 2]
  embed_dim: 16
  mlp_ratio: 4
  token_projection: 'linear'
  token_mlp: 'leff'
  modulator: True
  shift_flag: False

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0.02
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-6
    # gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: classswin
    # project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
