# general settings
name: 003_SwinIR_branch3_P416W8_DIV2Kclass3_500k_B4G1
model_type: SwinIRModel
scale: 1
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset

    
    dataroot_gt: /home/yqliu/projects/ClassSwin/data/Dehaze_select/clear
    # dataroot_gt: ../data/DIV2K_scale_sub_psnr_GT_class2.lmdb
    dataroot_lq: /home/yqliu/projects/ClassSwin/data/Dehaze_select/hazy_single
    # dataroot_lq: ../data/DIV2K_scale_sub_psnr_GT_class2.lmdb
    meta_info_file: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 416
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 3
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /home/yqliu/datasets/Set5/HR
    dataroot_lq: /home/yqliu/datasets/Set5/LRbicx4
    io_backend:
      type: disk

# network structures
network_g:
  type: SwinIR
  upscale: 1
  in_chans: 3
  img_size: 416
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: none
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    # project: ClassSwin
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
